#!/usr/bin/env node
/**
 * Copies the shipped font files out of the @fontsource packages into public/fonts/
 * and regenerates src/styles/fonts.css from the same manifest, so the @font-face
 * rules can never drift from the files that are actually deployed.
 *
 * Run: pnpm fonts
 */
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import subsetFont from 'subset-font';
import { decompress } from 'wawoff2';

import { FONT_FILES, LATIN_RANGE, OG_FONTS, TEXT_CHARSET } from './font-manifest.mjs';

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public', 'fonts');

let copied = 0;
for (const f of FONT_FILES) {
  const source = await readFile(require.resolve(f.from));
  const bytes = f.subsetText
    ? await subsetFont(source, f.subsetText, { targetFormat: 'woff2' })
    : source;

  const dest = join(outDir, f.to);
  await mkdir(dirname(dest), { recursive: true });
  await writeFile(dest, bytes);
  copied += 1;

  const note = f.subsetText
    ? ` ${(source.length / 1024).toFixed(0)} KB -> ${(bytes.length / 1024).toFixed(1)} KB` +
      ` (${[...new Set(f.subsetText)].length} glyphs)`
    : ` ${(bytes.length / 1024).toFixed(0)} KB`;
  console.log(`  ${f.to.padEnd(52)}${note}${f.preload ? '  [preload]' : ''}`);
}

const face = (f) => `@font-face{
  font-family:'${f.family}';
  font-style:${f.style};
  font-weight:${f.weight};
  font-display:swap;
  src:url('/fonts/${f.to}') format('woff2');
  unicode-range:${LATIN_RANGE};
}`;

/*
 * TTF copies for the OG-image renderer. satori cannot read woff2, so these are
 * decompressed from the very same subset files the browser gets — the card and
 * the page are guaranteed to have identical glyph coverage.
 *
 * .og-fonts/ is build-only and never served: an OG card is rendered at build
 * time, so no visitor ever needs these bytes.
 */
const ogDir = join(root, '.og-fonts');
await mkdir(ogDir, { recursive: true });
for (const font of OG_FONTS) {
  const woff2 = await readFile(join(outDir, font.from));
  let ttf = Buffer.from(await decompress(woff2));

  if (font.pinWeight) {
    // Instance the variable axis away; satori cannot parse a variable font.
    ttf = await subsetFont(ttf, TEXT_CHARSET, {
      targetFormat: 'truetype',
      variationAxes: { wght: { min: font.pinWeight, max: font.pinWeight, default: font.pinWeight } },
    });
  }

  await writeFile(join(ogDir, font.to), ttf);
  console.log(
    `  .og-fonts/${font.to.padEnd(24)} ${(ttf.length / 1024).toFixed(1).padStart(6)} KB` +
      (font.pinWeight ? `  (wght pinned to ${font.pinWeight})` : ''),
  );
}

const css = `/* GENERATED by scripts/sync-fonts.mjs — do not edit by hand.
   Edit scripts/font-manifest.mjs and run \`pnpm fonts\`.

   Only the \`latin\` subset is shipped: Google's latin unicode-range contains
   U+02BB-02BC, so Uzbek Oʻ / Gʻ / ʼ render in the same face as the text around
   them. Verified by scripts/check-glyphs.mjs on every build. */

${FONT_FILES.map(face).join('\n\n')}
`;

await writeFile(join(root, 'src', 'styles', 'fonts.css'), css, 'utf8');
console.log(`\n${copied} font files -> public/fonts/, src/styles/fonts.css regenerated.`);
